name: build
on:
  workflow_dispatch:
  schedule:
    # Run hourly (* is a special character in YAML, so quote the string)
    - cron:  '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Run
      run: |
        TIMESTAMP="$(date +%Y%m%d%H%M)"
        pip install neuralart
        neuralart             \
          --xlim -2 2         \
          --ylim -0.5 0.5     \
          --xres 8192         \
          --color-space bw    \
          --depth 11          \
          --output-std 1.5    \
          --hidden-std 1.1    \
          --seed "$TIMESTAMP" \
          neuralart.png
        git config user.name 'neuralart'
        git config user.email '<>'
        git checkout -b "$TIMESTAMP"
        git add neuralart.png
        git commit -m 'Automatic commit: Add neuralart.png'
        git push origin "$TIMESTAMP"
        git checkout main
        cat README.md.template | sed s/\$TIMESTAMP/$TIMESTAMP/ > README.md
        git add README.md
        git commit -m 'Automatic commit: Update README.md'
        git push origin main
